import { Code, Globe, Laptop, Layout, LucideIcon, Smartphone, Palette, Shield, Zap } from "lucide-react";

export interface Project {
  id: string;
  title: string;
  category: "Web" | "Mobile" | "AI" | "Security";
  thumbnail: string;
  description: string;
  tags: string[];
  caseStudy: {
    problem: string;
    solution: string;
    techStack: string[];
    outcome: string;
  };
}

export interface Skill {
  name: string;
  level: number;
  icon: LucideIcon;
}

export interface Testimonial {
  id: string;
  name: string;
  role: string;
  content: string;
  avatar: string;
}

export interface Award {
  id: string;
  title: string;
  issuer: string;
  year: string;
}

export const projects: Project[] = [
  {
    id: "1",
    title: "SaaS Analytics Dashboard",
    category: "Web",
    thumbnail: "https://storage.googleapis.com/dala-prod-public-storage/generated-images/9caa052d-5c2d-4319-9d5b-c4b8bc9b3384/project-saas-dashboard-6e872ae0-1779748577781.webp",
    description: "A high-performance dashboard for real-time data visualization and business intelligence.",
    tags: ["React", "TypeScript", "D3.js", "Tailwind"],
    caseStudy: {
      problem: "Client needed a way to visualize millions of data points without sacrificing performance.",
      solution: "Implemented canvas-based rendering and optimized data fetching with React Query.",
      techStack: ["React", "TypeScript", "D3.js", "PostgreSQL"],
      outcome: "Reduced load times by 60% and increased user engagement by 40%."
    }
  },
  {
    id: "2",
    title: "Fintech Mobile Wallet",
    category: "Mobile",
    thumbnail: "https://storage.googleapis.com/dala-prod-public-storage/generated-images/9caa052d-5c2d-4319-9d5b-c4b8bc9b3384/project-fintech-app-fe138710-1779748577517.webp",
    description: "Secure and intuitive mobile application for managing personal finances and crypto assets.",
    tags: ["React Native", "Firebase", "Stripe"],
    caseStudy: {
      problem: "Traditional banking apps were too complex for young users.",
      solution: "Designed a minimalist UI with one-tap transactions and social splitting features.",
      techStack: ["React Native", "Expo", "Node.js", "Redis"],
      outcome: "Top 50 in Finance category on App Store within 3 months."
    }
  },
  {
    id: "3",
    title: "Eco-Friendly Furniture Store",
    category: "Web",
    thumbnail: "https://storage.googleapis.com/dala-prod-public-storage/generated-images/9caa052d-5c2d-4319-9d5b-c4b8bc9b3384/project-furniture-store-90376fff-1779748576608.webp",
    description: "Full-stack e-commerce platform with AR product preview and sustainable shipping tracking.",
    tags: ["Next.js", "Three.js", "Shopify API"],
    caseStudy: {
      problem: "Furniture shopping online suffers from uncertainty about size and fit.",
      solution: "Integrated WebGL/Three.js for real-time 3D product visualization in users' rooms.",
      techStack: ["Next.js", "Three.js", "Tailwind", "Sanity CMS"],
      outcome: "Return rate decreased by 25% due to better visualization."
    }
  },
  {
    id: "4",
    title: "Cyber Threat Monitor",
    category: "Security",
    thumbnail: "https://storage.googleapis.com/dala-prod-public-storage/generated-images/9caa052d-5c2d-4319-9d5b-c4b8bc9b3384/project-cyber-security-4d3b8a07-1779748577210.webp",
    description: "Enterprise-grade security platform for real-time threat detection and mitigation.",
    tags: ["Go", "Python", "React", "Docker"],
    caseStudy: {
      problem: "Security teams overwhelmed by false positives from legacy systems.",
      solution: "Developed an AI-driven filter that categorizes threats based on severity and pattern analysis.",
      techStack: ["Go", "Python", "TensorFlow", "React"],
      outcome: "Reduced response time to critical threats from hours to minutes."
    }
  },
  {
    id: "5",
    title: "AI Travel Planner",
    category: "AI",
    thumbnail: "https://storage.googleapis.com/dala-prod-public-storage/generated-images/9caa052d-5c2d-4319-9d5b-c4b8bc9b3384/project-travel-ai-140a7a94-1779748576504.webp",
    description: "Personalized travel itineraries generated by Large Language Models based on user preferences.",
    tags: ["OpenAI", "Next.js", "Mapbox"],
    caseStudy: {
      problem: "Travel planning is time-consuming and generic.",
      solution: "Used GPT-4 to generate hyper-personalized itineraries with live weather and flight data.",
      techStack: ["Next.js", "OpenAI API", "Mapbox GL", "tRPC"],
      outcome: "Over 10,000 itineraries generated in the first month."
    }
  }
];

export const skills: Skill[] = [
  { name: "Frontend Architecture", level: 95, icon: Layout },
  { name: "Full Stack Development", level: 90, icon: Code },
  { name: "UI/UX Design", level: 85, icon: Palette },
  { name: "Cloud Infrastructure", level: 80, icon: Zap },
  { name: "Security Auditing", level: 75, icon: Shield },
  { name: "Mobile Development", level: 85, icon: Smartphone }
];

export const testimonials: Testimonial[] = [
  {
    id: "1",
    name: "Sarah Johnson",
    role: "CEO at TechFlow",
    content: "An absolute professional. The dashboard built for us exceeded all expectations in terms of performance and aesthetics.",
    avatar: "https://storage.googleapis.com/dala-prod-public-storage/generated-images/9caa052d-5c2d-4319-9d5b-c4b8bc9b3384/testimonial-user-1-b4dca25a-1779748577607.webp"
  },
  {
    id: "2",
    name: "Michael Chen",
    role: "Product Manager at InnovateX",
    content: "Rarely do you find a developer who understands both the technical constraints and the user needs so deeply.",
    avatar: "https://storage.googleapis.com/dala-prod-public-storage/generated-images/9caa052d-5c2d-4319-9d5b-c4b8bc9b3384/testimonial-user-2-12e8ee97-1779748577703.webp"
  }
];

export const awards: Award[] = [
  { id: "1", title: "Top Developer 2023", issuer: "GitHub Universe", year: "2023" },
  { id: "2", title: "Excellence in UI Design", issuer: "Awwwards", year: "2022" },
  { id: "3", title: "Best Open Source Contributor", issuer: "Meta", year: "2021" }
];